#!/bin/bash

python3 src/create_model.py bab
python3 src/create_model.py bac
python3 src/create_model.py cha
python3 src/create_model.py csa
python3 src/create_model.py cya
python3 src/create_model.py cyb
python3 src/create_model.py cza
python3 src/create_model.py hja
python3 src/create_model.py hjc
python3 src/create_model.py joa
python3 src/create_model.py kaa
python3 src/create_model.py kab
python3 src/create_model.py kka
python3 src/create_model.py ksa
python3 src/create_model.py kta
python3 src/create_model.py kyg
python3 src/create_model.py kyh
python3 src/create_model.py kyi
python3 src/create_model.py kza
python3 src/create_model.py msa
python3 src/create_model.py mza
python3 src/create_model.py ot
python3 src/create_model.py ou
python3 src/create_model.py ov
python3 src/create_model.py ow
python3 src/create_model.py oz
python3 src/create_model.py sec
python3 src/create_model.py secsoku
python3 src/create_model.py sed
python3 src/create_model.py skb
python3 src/create_model.py sra
python3 src/create_model.py srb
python3 src/create_model.py tyb
python3 src/create_model.py ukc
python3 src/create_model.py zec
python3 src/create_model.py zkb
