#!/bin/bash
set -e
cd spec
wget http://www.jrdb.com/program/Kta/kta_doc.txt -O kta.txt
wget http://www.jrdb.com/program/Sed/sed_doc.txt -O sed.txt
wget http://www.jrdb.com/program/Sec/sec_doc.txt -O sec.txt
wget http://www.jrdb.com/program/Skb/skb_doc.txt -O skb.txt
wget http://www.jrdb.com/program/Srb/srb_doc.txt -O srb.txt
wget http://www.jrdb.com/program/Sra/sra_doc.txt -O sra.txt
wget http://www.jrdb.com/program/Cs/Cs_doc1.txt  -O cza.txt
wget http://www.jrdb.com/program/Cs/Cs_doc1.txt  -O csa.txt
wget http://www.jrdb.com/program/Ks/Ks_doc1.txt  -O kza.txt
wget http://www.jrdb.com/program/Ks/Ks_doc1.txt  -O ksa.txt
wget http://www.jrdb.com/program/Msa/msa_doc.txt  -O mza.txt
wget http://www.jrdb.com/program/Msa/msa_doc.txt  -O msa.txt
wget http://www.jrdb.com/program/Kyi/kyi_doc.txt -O kyi.txt
wget http://www.jrdb.com/program/Kyh/kyh_doc.txt -O kyh.txt
wget http://www.jrdb.com/program/Kyg/kyg_doc.txt -O kyg.txt
wget http://www.jrdb.com/program/Kka/kka_doc.txt -O kka.txt
wget http://www.jrdb.com/program/Ukc/ukc_doc.txt -O ukc.txt
wget http://www.jrdb.com/program/Jo/Jodata_doc2.txt -O joa.txt
wget http://www.jrdb.com/program/Oz/Ozdata_doc.txt -O oz.txt
wget http://www.jrdb.com/program/Oz/Owdata_doc.txt -O ow.txt
wget http://www.jrdb.com/program/Ou/Oudata_doc.txt -O ou.txt
wget http://www.jrdb.com/program/Ot/Otdata_doc.txt -O ot.txt
wget http://www.jrdb.com/program/Ov/ovdata_doc.txt -O ov.txt
wget http://www.jrdb.com/program/Zec/zec_doc.txt -O zec.txt
wget http://www.jrdb.com/program/Zkb/zkb_doc.txt -O zkb.txt
wget http://www.jrdb.com/program/Kab/kab_doc.txt -O kab.txt
wget http://www.jrdb.com/program/Kaa/kaa_doc.txt -O kaa.txt
wget http://www.jrdb.com/program/Bac/bac_doc.txt -O bac.txt
wget http://www.jrdb.com/program/Bab/bab_doc.txt -O bab.txt
wget http://www.jrdb.com/program/Cyb/cyb_doc.txt -O cyb.txt
wget http://www.jrdb.com/program/Cya/cya_doc.txt -O cya.txt
wget http://www.jrdb.com/program/Cha/cha_doc.txt -O cha.txt
wget http://www.jrdb.com/program/Tyb/tyb_doc.txt -O tyb.txt
wget http://www.jrdb.com/program/Hjc/hjcdata_doc.txt -O hjc.txt
wget http://www.jrdb.com/program/Hj/hja_doc.txt -O hja.txt
wget http://www.jrdb.com/program/Sec/secsoku_doc.txt -O secsoku.txt