#!/bin/bash

python3 src/trim_spec.py bab
python3 src/trim_spec.py bac
python3 src/trim_spec.py cha
python3 src/trim_spec.py csa
python3 src/trim_spec.py cya
python3 src/trim_spec.py cyb
python3 src/trim_spec.py cza
python3 src/trim_spec.py hja
python3 src/trim_spec.py hjc
python3 src/trim_spec.py joa
python3 src/trim_spec.py kaa
python3 src/trim_spec.py kab
python3 src/trim_spec.py kka
python3 src/trim_spec.py ksa
python3 src/trim_spec.py kta
python3 src/trim_spec.py kyg
python3 src/trim_spec.py kyh
python3 src/trim_spec.py kyi
python3 src/trim_spec.py kza
python3 src/trim_spec.py msa
python3 src/trim_spec.py mza
python3 src/trim_spec.py ot
python3 src/trim_spec.py ou
python3 src/trim_spec.py ov
python3 src/trim_spec.py ow
python3 src/trim_spec.py oz
python3 src/trim_spec.py sec
python3 src/trim_spec.py secsoku
python3 src/trim_spec.py sed
python3 src/trim_spec.py skb
python3 src/trim_spec.py sra
python3 src/trim_spec.py srb
python3 src/trim_spec.py tyb
python3 src/trim_spec.py ukc
python3 src/trim_spec.py zec
python3 src/trim_spec.py zkb
